
server:
  port: 80

spring:
  application:
    name: cloud-consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8082
        port: 8719

swagger:
  enable: true

##服务调用地址
server-url:
  provider-service-url: http://localhost:8001/Iteminfo




management:
  endpoints:
    web:
      exposure:
        include: '*'



